version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

#docker build -t flask-app .
#docker run -p 5001:5000 flask-app
#docker-compose up --build

#sudo lsof -i :5000
#sudo kill -9 <PID>